name: my_time_tracker
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.0.1
  animated_text_kit: ^4.2.1
  cloud_firestore: ^2.4.0
  connectivity: ^3.0.3
  country_codes: ^2.0.1
  data_connection_checker: ^0.3.4
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.0
  firebase_storage: ^8.0.2

  flutter_native_splash: ^1.1.5+1
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  google_sign_in: ^4.5.6
  intl_phone_number_input: ^0.7.0+2
  flutter_facebook_login: ^3.0.0
  image_picker: ^0.8.4+2
  legacy_progress_dialog: ^0.0.9
  open_mail_app: ^0.2.0
  pinput: ^1.2.0
  provider: ^5.0.0
  rxdart: ^0.23.1
  user_profile_avatar: ^0.0.9
  empty_widget: ^0.0.5
  argon_buttons_flutter: ^1.1.0
  adaptive_action_sheet: ^2.0.0

dependency_overrides:
  libphonenumber: ^2.0.2



flutter_native_splash:
  color: "#005430"
  image: images/Time_tracker/1.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/google-logo.png
    - images/facebook-logo.png
    - images/4.svg
    - images/5.svg
    - images/Time_tracker/time_tracker_logo.svg
    - images/Time_tracker/time_tracker_title.svg
    - images/Time_tracker/1.png
    - images/EmptyOrangeBox.png
    - assets/images/emptyImage.png
    - assets/images/im_emptyIcon_1.png
    - assets/images/im_emptyIcon_2.png
    - assets/images/im_emptyIcon_3.png

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
